add_newline = false
format = """$directory$git_branch$git_status$character"""
right_format = """$all"""

[character]
success_symbol = '[â¯](bold #42f56c)'
error_symbol = '[â¯](bold red)' #âœ—

[line_break]
disabled = true

[directory]
style = '#00a5ff bold'
truncation_length = 1
truncate_to_repo = false

[git_branch]
format = "[âŸ¨$branchâŸ©]($style)"
style = " bright-black"
#style = " #f0a030"

[git_status]
format = ' ([$all_status$ahead_behind]($style) )' #âŸ¨âŸ©
style = "bold #f0a030"
stashed = '*${count}'
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•${count}"
conflicted = "=${count}"
deleted = "âœ˜${count}"
renamed = "Â»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"

[aws]
format = '| [($profile )(\($region\) )]($style) '
style = 'bold cyan'
#symbol = 'ğŸ…°  '

[python]
format = '(bold green)[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = 'py' # ó°Œ   ğŸ ğŸ‘¾  |
style = 'bright-purple'
version_format = '${major}.${minor}'
disabled = false

